version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    assignees:
      - cedricziel
    schedule:
      interval: "daily"
    ignore:
      # These are peer deps of Cargo and should not be automatically bumped
      - dependency-name: "semver"
      - dependency-name: "crates-io"
    rebase-strategy: "disabled"
    groups:
      leptos:
        patterns:
          - "leptos*"
