[workspace]
resolver = "2"

members = ["leptos-charming"]
exclude = ["examples"]

[workspace.dependencies]
charming = { git = "https://github.com/cedricziel/charming.git", branch = "cloneable" }
leptos = "0.6.15"
leptos_meta = "0.6.15"
rand = "0.8"
web-sys = "0.3"
